default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ruby_llm_development
  username: madhav
  password: admin123
  host: localhost

test:
  <<: *default
  database: ruby_llm_test
  username: madhav
  password: admin123
  host: localhost